### PR TITLE
fill out controller documentation

### PR DESCRIPTION
**Pull request by Gabe-Mitnick**
also fix naming naming of some buttons and change "outake" to "outtake"

### CODE REVIEW

**Comment by Gabe-Mitnick** [comment]
fixed a merge conflict where i had changed some names referenced in lines which were newly commented out. now the pull request has those lines commented out, but with the new names.

**Comment by Gabe-Mitnick** [comment]
now it has the left and right joystick axes too. (before i just did buttons.)

**Comment by brettle** [comment]
@Gabe-Mitnick can you resolve the conflicts in your fork and then re-commit and push so that we can merge cleanly?

**Comment by Gabe-Mitnick** [comment]
@brettle it's good to go

**Pull request merged**
